steps:
  # Step to clone code from GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/obeki/cloud-function-test.git']

  - name: 'gcr.io/insurance-proj-1/us-central1-docker.pkg.dev/insurance-proj-1/cloud-builder/zipper'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd cloud-function-test
        zip -r ssss.zip .

 # - name: 'bash'
 #   args: ['-c', 'cd cloud-function-test && zip -r my_archive.zip *']



  # Step to copy the zipped code to Cloud Storage bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pwd
        cd ..
        ls -l
        gsutil cp ssss.zip gs://deuteronomy/project_files.zip

# Optional: Define substitutions to pass variables to the build
substitutions:
  _BUCKET_NAME: deuteronomy

