steps:
  # Step to clone code from GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/obeki/cloud-function-test.git', '/repo']

  - name: 'bash'
    args: ['-c', 'cd /repo && zip -r my_archive.zip *']



  # Step to copy the zipped code to Cloud Storage bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp repo.zip gs://deuteronomy/project_files.zip

# Optional: Define substitutions to pass variables to the build
substitutions:
  _BUCKET_NAME: deuteronomy

