steps:
  # Step to clone code from GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/obeki/cloud-function-test.git project_files

  # Step to zip the code
  - name: 'gcr.io/cloud-builders/zip'
    entrypoint: 'bash'
    args:
      - '-r'
      - 'project_files.zip'
      - 'project_files'


  # Step to copy the zipped code to Cloud Storage bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp project_files.zip gs://santabarta/project_files.zip

# Optional: Define substitutions to pass variables to the build
substitutions:
  _BUCKET_NAME: santabarta

options:
  logging: CLOUD_LOGGING_ONLY
