steps:
  # Step to clone code from GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/obeki/cloud-function-test.git']

  - name: 'gcr.io/insurance-proj-1/us-central1-docker.pkg.dev/insurance-proj-1/cloud-builder/zipper'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        #ls
        cd cloud-function-test
        zip -r ssss.zip .
        #ls
        #pwd

 # - name: 'bash'
 #   args: ['-c', 'cd cloud-function-test && zip -r my_archive.zip *']



  # Step to copy the zipped code to Cloud Storage bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        #pwd
        #cd ..
        #ls -l
        gsutil cp cloud-function-test/ssss.zip gs://deuteronomy/project_files.zip


  # Step to deploy the Cloud Function to Cloud Function Gen 2
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy my-cloud-function \
          --entry-point=hello_gcs \
          --runtime=python311 \
          --trigger-resource=bucket-gen-1 \
          --trigger-event=google.cloud.storage.object.v1.finalized \
          --source=gs://deuteronomy/project_files.zip \
          --region=us-central1 \
          --project=insurance-proj-1
          --gen2

          
# Optional: Define substitutions to pass variables to the build
substitutions:
  _BUCKET_NAME: deuteronomy

